version: '3'

services:
  microservicio:
    build: .
    ports:
      - "8000:8000" #puerto primera replica
      - "8001:8000" #puerto segunda replica
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
