version: '3.8'

services:
  microservicio:
    build: .
    ports:
      - "8000:8000"  # Exponemos solo una vez el puerto
    deploy:
      mode: replicated
      replicas: 2  # Docker Swarm balanceará automáticamente
      restart_policy:
        condition: on-failure

